---
name: clippy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain with clippy
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --workspace -- -D warnings
